server.port: 9004

spring:
  application:
    name: software-board-hot-article-service

  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092 # broker server 의 주소 .
    consumer:
      group-id: software-board-hot-article-service # 인기글 설정을 위한 컨슈머 그룹
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

endpoints:
  software-board-article-service:
    url: http://localhost:9000
